# SORRY, still work in progress, very messy and not finished

In [32]:
import sys
import os
import cv2
import numpy as np
import matplotlib.pyplot as plt
import c3d
import importlib
from typing import List

# Import RGB_helpers
sys.path.append('/app/hpe-core/datasets/vicon_processing/v2')
import RGB_helpers

In [45]:
vicon_c3d_file: str = '/home/cappe/hpe/RGB_calibration/VICON/test9/test901.c3d'
RGB_folder: str = '/home/cappe/hpe/RGB_calibration/test9/rgb.mp4'
calib_path: str = '/home/cappe/hpe/RGB_calibration/color_camera.yaml' 
cap = cv2.VideoCapture(RGB_folder)
fps = cap.get(cv2.CAP_PROP_FPS)
period: float = 1.0 / fps  # vicon frequency: 100HZ
input_label_tag_file: str = '../scripts/config/labels_tags_vicon.yml'
output_label_yml_file: str = '/home/cappe/hpe/RGB_calibration/labels_RGB_test7.yml'

### Import RGB data and calibration

In [34]:
import os
import yaml
import numpy as np

def load_camera_calibration(yaml_path, camera="color"):
    with open(yaml_path, "r") as f:
        data = yaml.safe_load(f)

    if data.get("camera_name", "") != camera:
        print(f"Warning: loaded camera_name={data.get('camera_name')} but expected {camera}")

    # Camera intrinsics
    K = np.array(data["camera_matrix"]["data"], dtype=np.float64).reshape(3, 3)

    # Distortion coefficients
    D = np.array(data["distortion_coefficients"]["data"], dtype=np.float64).reshape(-1, 1)

    width = data.get("image_width", None)
    height = data.get("image_height", None)

    return K, D, (width, height)


# Open video (reuse RGB_folder from previous cell)
cap = cv2.VideoCapture(RGB_folder)
if not cap.isOpened():
    raise RuntimeError(f"Cannot open video: {RGB_folder}")

# Read video metadata and set period
fps = cap.get(cv2.CAP_PROP_FPS) or 100.0
frame_count = int(cap.get(cv2.CAP_PROP_FRAME_COUNT) or 0)
w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH) or 0)
h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT) or 0)
period = 1.0 / float(fps) if fps > 1e-6 else 1.0 / 100.0

# Image sizes used elsewhere: cam_res = (H,W) for grayscale/event buffers
cam_res = (h, w)
cam_res_rgb = (h, w, 3)

print(f"Video: {frame_count} frames, {fps:.2f} FPS, size={w}x{h} -> period={period:.6f}s")

K, D, (w_calib, h_calib) = load_camera_calibration(calib_path, camera="color")

print("K:\n", K)
print("D:\n", D)
print("Image size:", (w_calib, h_calib))

print("Camera matrix:\n", K)
print("Distortion coeffs:", D)
print("cam_res:", cam_res)


cap = cv2.VideoCapture(RGB_folder)  # RGB_folder = path to .mp4 or .avi
if not cap.isOpened():
    raise RuntimeError(f"Cannot open video: {RGB_folder}")

fps = cap.get(cv2.CAP_PROP_FPS) or 30.0
frame_count = int(cap.get(cv2.CAP_PROP_FRAME_COUNT) or 0)
w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH) or 0)
h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT) or 0)
period = 1.0 / fps

print(f"Video: {frame_count} frames, {fps:.2f} FPS, {w}x{h}")

Video: 2545 frames, 30.00 FPS, size=1280x720 -> period=0.033333s
K:
 [[920.57775879   0.         643.53894043]
 [  0.         918.72113037 353.19778442]
 [  0.           0.           1.        ]]
D:
 [[0.]
 [0.]
 [0.]
 [0.]
 [0.]]
Image size: (1280, 720)
Camera matrix:
 [[920.57775879   0.         643.53894043]
 [  0.         918.72113037 353.19778442]
 [  0.           0.           1.        ]]
Distortion coeffs: [[0.]
 [0.]
 [0.]
 [0.]
 [0.]]
cam_res: (720, 1280)
Video: 2545 frames, 30.00 FPS, 1280x720


### Import C3D data

In [46]:
c3d_data = c3d.Reader(open(vicon_c3d_file, 'rb'))
points_3d: dict = {}
for i, points, analog in c3d_data.read_frames():
    points_3d[i] = points

marker_t = np.linspace(0.0, c3d_data.frame_count / c3d_data.point_rate, 
                            c3d_data.frame_count, endpoint=False)

c3d_data.point_labels

marker_names = [f"{name}" for name in c3d_data.point_labels]
marker_names = [name.strip() for name in marker_names]

marker_names

['stereoatis:cam_right',
 'stereoatis:cam_back',
 'stereoatis:cam_left',
 'monitor:Origin_mon_top_right',
 'monitor:mon_bottom_right',
 'monitor:mon_bottom_left',
 'monitor:mon_top_left',
 'monitor:base_origin_1',
 'monitor:base_2',
 'monitor:base_3',
 'monitor:base_4',
 'chair:origin_right_top',
 'chair:right_mid',
 'chair:right_bottom',
 'chair:left_top',
 'chair:left_bottom',
 'box2:top_right_Origin',
 'box2:bottom_right',
 'box2:bottom_left',
 'box2:top_left',
 'box1:top_1_origin',
 'box1:top_2',
 'box1:top_3',
 'box1:top_4',
 'box1:bottom_1',
 'box1:bottom_2',
 'box1:bottom_3',
 'box1:bottom_4',
 '*28']

### Initial delay definition

In [10]:
delay = -0.01     # idk, it's weird so check

In [47]:
#TODO: get init files

# if file exists, load transforamtion and delay, otherwise run the next cells

import os
import numpy as np

# file = "/home/cappe/hpe/move-iit-hpe-subset1/P1/tennis_s1/init_file.txt"
file = "/home/cappe/hpe/RGB_calibration/init_file_rgb.txt"

if os.path.exists(file):
    with open(file, 'r') as f:
        content = f.read().splitlines()

    # Extract transformation matrix
    start = content.index("[TRANSFORMATION MATRIX SYSTEM TO CAMERA]") + 1
    end = content.index("[DELAY]")  # matrix stops before delay tag
    matrix_lines = content[start:end]

    matrix = []
    for line in matrix_lines:
        # clean brackets [[ ]] and []
        clean = line.replace("[[", "").replace("]]", "").replace("[", "").replace("]", "")
        row = [float(x) for x in clean.strip().split() if x]
        if row:
            matrix.append(row)

    T_syst_to_camera_opt = np.array(matrix, dtype=np.float64)

    # Extract delay (skip empty lines after [DELAY])
    delay_index = content.index("[DELAY]") + 1
    while delay_index < len(content) and not content[delay_index].strip():
        delay_index += 1
    delay = float(content[delay_index].strip())
else:
    print("Init file not found, please run the initialization cells.")
    T_syst_to_camera_opt = np.eye(4)
    delay = 0.0
    
print("SystemToCamera T:\n", T_syst_to_camera_opt)
print("Delay:", delay)


SystemToCamera T:
 [[ 5.77034423e-01 -6.43217951e-01  5.03291110e-01 -1.81915332e+00]
 [-4.03108609e-01 -7.60246335e-01 -5.09439848e-01 -1.34553317e+01]
 [ 7.10306078e-01  9.10833489e-02 -6.97974999e-01 -1.10096055e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Delay: -0.073


### Label sequence

In [6]:
import importlib
import os
import cv2
import numpy as np

importlib.reload(RGB_helpers)
from RGB_helpers import RGBLabeler

# Path setup
labels_path = os.path.join(os.path.dirname(vicon_c3d_file), output_label_yml_file)

# Choose labeling period (seconds per labeling step, e.g. 0.05s = 20Hz)
period = 0.05  

# Initialize labeler with video file
labeler = RGBLabeler(video_path=RGB_folder, subject="camera")

# Run interactive labeling
labeled_dict = labeler.label_video(RGB_folder, period)

# Save labeled points to YAML
labeler.save_labeled_points(labels_path)

print("Saved labeled points at:", labels_path)

cv2.destroyAllWindows()

current labels: {'camera:box1:bottom_1': {'x': 670, 'y': 362}}
Removed last labeled marker.
current labels: {'camera:box1:bottom_1': {'x': 667, 'y': 360}}
current labels: {'camera:box1:bottom_1': {'x': 667, 'y': 360}, 'camera:box1:top_1_origin': {'x': 606, 'y': 28}}
current labels: {'camera:box1:bottom_1': {'x': 667, 'y': 360}, 'camera:box1:top_1_origin': {'x': 606, 'y': 28}, 'camera:box1:top_2': {'x': 294, 'y': 184}}
space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, skipping
sp

### Load labels and calculate transformation matrix from system to camera using scipy optimizer

In [6]:
from scipy.optimize import least_squares

def reprojection_error(params, Ps, pc, K, dist):
    """
    params: 6 dimensions (rotation_vector [3], translation [3]) Optimization target
    Ps: (N, 3) 3D points (system coordinates)
    pc: (N, 2) 2D points (image coordinates)
    K: (3, 3) camera matrix
    dist: (5,) distortion parameters (OpenCV format)
    """
    rvec = params[:3]
    tvec = params[3:6]

    # Project 3D system points to 2D image points
    projected_points, _ = cv2.projectPoints(Ps, rvec, tvec, K, dist)
    projected_points = projected_points.reshape(-1, 2)

    return (projected_points - pc).ravel()  # Flatten and return


def estimate_Tstoc(Ps, pc, K, dist, init_params=None):
    """
    Ps: (N, 3) 3D points (system coordinates)
    pc: (N, 2) 2D points (image coordinates)
    K: (3, 3) camera matrix
    dist: (5,) distortion parameters
    return: (4, 4) system→camera coordinate transformation matrix Tstoc
    """

    # Initial values: zero rotation, zero translation
    if init_params is None:
        # If no initial parameters are provided, set them to zero
        init_params = np.zeros(6)

    # Minimize (choose LM method, etc.)
    res = least_squares(
        reprojection_error,
        init_params,
        args=(Ps, pc, K, dist),
        method='lm'  # Levenberg-Marquardt
    )

    rvec_opt = res.x[:3]
    tvec_opt = res.x[3:6]
    R_opt, _ = cv2.Rodrigues(rvec_opt)

    # Construct homogeneous transformation matrix
    T = np.eye(4)
    T[:3, :3] = R_opt
    T[:3, 3] = tvec_opt

    return T

In [7]:
importlib.reload(RGB_helpers)
from RGB_helpers import ViconHelperRGB

# Define vicon helper
print("Delay: ", delay) # Please adjust delay manually
vicon_helper = ViconHelperRGB(marker_t, points_3d, delay, c3d_data.frame_count, c3d_data.point_rate, c3d_data.point_labels, True, True) # if needed create the function to call instead of None

# Load labeled points
labels_path = os.path.join(os.path.dirname(vicon_c3d_file), output_label_yml_file)
labeled_points = RGB_helpers.read_points_labels(labels_path) # read labeled points from the yaml file

# extract the frames_id from the labeled points
frames_id = vicon_helper.get_frame_time(labeled_points['times'])
vicon_points = vicon_helper.get_vicon_points_interpolated(labeled_points)
# print("First few label dicts from YAML:")
# for i, d in enumerate(labeled_points['points']):
#     print(f"Frame {i}: {d}")

# Create lists of transformation matrix from world to system
system_points = []
image_points = []
Ts_system_to_camera: List[np.ndarray] = []
Ts_world_to_system = vicon_helper.compute_camera_marker_transforms()

# Collect correspondences from 3D system points to 2D image points
for idx, (dvs_frame, vicon_frame) in enumerate(zip(labeled_points['points'], vicon_points['points'])):
    labels = dvs_frame.keys()

    for l in labels:
        try:
            w_p = vicon_frame[l]
            w_ph = np.append(w_p, 1.0)  # homogeneous coordinates
            i_p = [
                dvs_frame[l]['x'],
                dvs_frame[l]['y'] #,
                # 1.0
            ]
            frame_id = vicon_points['frame_ids'][idx]
            p_sys = Ts_world_to_system[frame_id] @ w_ph  # convert to system coordinates
            system_points.append(p_sys[:3])
            image_points.append(i_p)
        except Exception as e:
            print("The stored image labels probably don't match with the vicon labels used.")
            print(e)
system_points = np.array(system_points, dtype=np.float64)
image_points = np.array(image_points, dtype=np.float64)
image_points = image_points[:, :2]



Delay:  -0.073
out {'points': [{'stereoatis:cam_right': array([-436.5234 ,  790.85315,  879.18604], dtype=float32), 'stereoatis:cam_back': array([-494.32202,  855.09015,  919.47534], dtype=float32), 'stereoatis:cam_left': array([-479.50995,  807.1114 ,  857.0858 ], dtype=float32)}, {'stereoatis:cam_right': array([-436.71155,  790.6289 ,  878.95746], dtype=float32), 'stereoatis:cam_back': array([-494.32016,  855.094  ,  919.4863 ], dtype=float32), 'stereoatis:cam_left': array([-479.55362,  807.0915 ,  857.0675 ], dtype=float32)}, {'stereoatis:cam_right': array([-436.28622,  791.00055,  879.47644], dtype=float32), 'stereoatis:cam_back': array([-494.31198,  855.1035 ,  919.4934 ], dtype=float32), 'stereoatis:cam_left': array([-479.54333,  807.1374 ,  857.12134], dtype=float32)}, {'stereoatis:cam_right': array([-436.49933,  790.81195,  879.1287 ], dtype=float32), 'stereoatis:cam_back': array([-494.31723,  855.12244,  919.48663], dtype=float32), 'stereoatis:cam_left': array([-479.5291 ,  80

### Static projection???

In [11]:
importlib.reload(RGB_helpers)

# Collect correspondences with better error handling and then do projection
world_points = []
image_points_clean = []

marker_names = ['box1:top_1_origin             ', 'box1:top_2                    ',
                'box1:top_3                    ', 'box1:top_4                    ',
                'box1:bottom_1                 ', 'box1:bottom_2                 ',
                'box1:bottom_3                 ', 'box1:bottom_4                 '] 

for idx, (dvs_frame, vicon_frame) in enumerate(zip(labeled_points['points'], vicon_points['points'])):
    labels = dvs_frame.keys()

    for l in labels:
        try:
            if l not in vicon_frame:
                print(f"Warning: Marker '{l}' not found in Vicon frame {idx}")
                continue
                
            w_p = vicon_frame[l]
            
            # Check if the point is valid (not NaN or None)
            if w_p is None or np.any(np.isnan(w_p)):
                print(f"Warning: Invalid 3D point for marker '{l}' in frame {idx}")
                continue
                
            i_p = [dvs_frame[l]['x'], dvs_frame[l]['y']]
            
            # Use world coordinates directly
            world_points.append(w_p)
            image_points_clean.append(i_p)
            
        except KeyError as e:
            print(f"KeyError: Marker '{l}' not found in Vicon data at frame {idx}")
        except Exception as e:
            print(f"Error processing marker '{l}': {e}")

world_points = np.array(world_points, dtype=np.float64)
image_points_clean = np.array(image_points_clean, dtype=np.float64)

print(f"Successfully collected {len(world_points)} valid 3D-2D correspondences")
print("World points shape:", world_points.shape)
print("Image points shape:", image_points_clean.shape)

# Solve PnP with world coordinates
success, rvec, tvec = cv2.solvePnP(world_points, image_points_clean, K, D)

if success:
    print("PnP solution successful!")
    
    # Convert to transformation matrix
    R_mat, _ = cv2.Rodrigues(rvec)
    T_world_to_cam = np.eye(4)
    T_world_to_cam[:3, :3] = R_mat
    T_world_to_cam[:3, 3] = tvec.flatten()
    
    print("World-to-camera transformation matrix:")
    print(T_world_to_cam)
    
    # Test projection of a few points
    if len(world_points) > 0:
        test_points = world_points[:min(5, len(world_points))]
        projected_test, _ = cv2.projectPoints(test_points, rvec, tvec, K, D)
        projected_test = projected_test.reshape(-1, 2)
        
        print("Test projections (first few points):")
        for i in range(len(projected_test)):
            print(f"3D: {test_points[i]} -> 2D projected: {projected_test[i]} (labeled: {image_points_clean[i]})")   

    print("Projecting markers onto event plane...")
    
    # TODO: adjust for RGB data
    projected_points_pnp = RGB_helpers.project_vicon_to_rgb_plane(
        marker_names, c3d_data, points_3d, marker_t, T_world_to_cam, 
        {i: np.eye(4) for i in range(len(marker_t))},  # Identity transforms since we're using world-to-camera directly
        K, RGB_folder, delay, D=D, visualize=True
    )
    
else:
    print("PnP solution failed!")
    print("Check that you have enough valid correspondences and that the points are not coplanar")

Successfully collected 592 valid 3D-2D correspondences
World points shape: (592, 3)
Image points shape: (592, 2)
PnP solution successful!
World-to-camera transformation matrix:
[[-6.62794895e-01  7.16095766e-01  2.18883032e-01 -1.21398663e+02]
 [ 3.74873918e-01  6.42815443e-02  9.24844543e-01 -1.23529099e+03]
 [ 6.48207122e-01  6.95035781e-01 -3.11051105e-01 -3.92233749e+03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Test projections (first few points):
3D: [ 560.98852539 1058.84130859  636.04125977] -> 2D projected: [520.34312144 465.33450973] (labeled: [767. 619.])
3D: [ 514.3961792  1410.35144043  642.89666748] -> 2D projected: [417.92744659 470.04614035] (labeled: [442. 605.])
3D: [ 509.93588257 1406.2121582   881.8638916 ] -> 2D projected: [407.51695876 397.13412757] (labeled: [440. 387.])
3D: [1810.83288574  774.78674316  854.31707764] -> 2D projected: [859.12562975 248.0109587 ] (labeled: [1016.  402.])
3D: [1816.3828125   764.99609375 1094.47827148] -> 

In [9]:
#TODO: change this so that it is not hardcoded bit instead generated by user inputs

# Create initial guess for the optimization
from scipy.spatial.transform import Rotation

# init_T = np.array([[ 5.54118388e-01, -6.46688971e-01, 5.24162298e-01, -1.25350531e+02],
#                    [-3.65516271e-01, -7.54740636e-01, -5.44760888e-01, -8.06780263e+00],
#                    [ 7.47897430e-01, 1.10272191e-01, -6.54591006e-01, -9.41323412e+01],
#                    [ 0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])

# init_T = np.array([[ 9.58177085e-01,  2.70140431e-01,  9.44500986e-02, -1.10010569e+03],
#                    [ 9.62649522e-02, -6.15063556e-01,  7.82578993e-01, -7.74416582e+02],
#                    [ 2.69499040e-01, -7.40757024e-01, -6.15344861e-01,  4.56237436e+02],
#                    [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

init_T = np.array([[ 5.61044044e-01, -6.49370788e-01,  5.13368445e-01,  6.86358081e+00],
                   [-3.95323336e-01, -7.55065991e-01, -5.23062912e-01, -2.47700684e+01],
                   [ 7.27288829e-01,  9.05148054e-02, -6.80336703e-01, -1.09117981e+02],
                   [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

#init_T = T_world_to_cam @ np.linalg.inv(Ts_world_to_system[0])

# init_T = np.array([[ 5.56691261e-01, -6.52984428e-01,  5.13523298e-01,         9.40228344e+00],       [-3.82826140e-01, -7.50269274e-01, -5.39017776e-01,        -4.41031645e+01],       [ 7.37250966e-01,  1.03476344e-01, -6.67647856e-01,        -1.09905442e+02],       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,         1.00000000e+00]])

# init_T = Ts_system_to_camera

r_vec = Rotation.from_matrix(init_T[:3, :3]).as_rotvec()
t_vec = init_T[:3, 3]
r_vec, t_vec, init_T
init_param = np.concatenate((r_vec, t_vec))
init_param

array([   2.44944516,   -0.85398513,    1.0141752 ,    6.86358081,
        -24.7700684 , -109.117981  ])

In [10]:
T_syst_to_camera_opt = estimate_Tstoc(system_points, image_points, K, D, init_param)
T_syst_to_camera_opt

#TODO: save the transformation matrix and the delay in a file

array([[ 5.77034423e-01, -6.43217951e-01,  5.03291110e-01,
        -1.81915332e+00],
       [-4.03108609e-01, -7.60246335e-01, -5.09439848e-01,
        -1.34553317e+01],
       [ 7.10306078e-01,  9.10833489e-02, -6.97974999e-01,
        -1.10096055e+02],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])

### Manual rotation adjustment

In [ ]:
marker_names = ['P1:LANK', 'P1:RANK', 'P1:LKNE', 'P1:RKNE', 'P1:RSHO', 'P1:LSHO', 'P1:LELB', 'P1:RELB', 'P1:LWRA', 'P1:RWRA', 'P1:CLAV', 'P1:STRN', 'P1:LFHD', 'P1:RFHD']
chosen_one = 'P1:CLAV'  # choose the marker to track

# TODO: adjust for RGB data

projected_points = RGB_helpers.project_and_manual_rotation(
    marker_names, c3d_data, points_3d, marker_t, np.eye(4), Ts_world_to_system, K, cam_res, delay, e_ts, e_us, e_vs, period, visualize=True, D=D, chosen_one=chosen_one
)

### Correct Delay by going though all frames

In [ ]:
importlib.reload(RGB_helpers)

#TODO: implement for rgb

# marker_names = ['stereoatis:cam_right          ', 'stereoatis:cam_back           ',
#        'stereoatis:cam_left           ', 'monitor:Origin_mon_top_right  ',
#        'monitor:mon_bottom_right      ', 'monitor:mon_bottom_left       ',
#        'monitor:mon_top_left          ', 'monitor:base_origin_1         ',
#        'monitor:base_2                ', 'monitor:base_3                ',
#        'monitor:base_4                ', 'chair:origin_right_top        ',
#        'chair:right_mid               ', 'chair:right_bottom            ',
#        'chair:left_top                ', 'chair:left_bottom             ',
#        'box2:top_right_Origin         ', 'box2:bottom_right             ',
#        'box2:bottom_left              ', 'box2:top_left                 ',
#        'box1:top_1_origin             ', 'box1:top_2                    ',
#        'box1:top_3                    ', 'box1:top_4                    ',
#        'box1:bottom_1                 ', 'box1:bottom_2                 ',
#        'box1:bottom_3                 ', 'box1:bottom_4                 ']

marker_names = ['P1:LANK', 'P1:RANK', 'P1:LKNE', 'P1:RKNE', 'P1:RSHO', 'P1:LSHO', 'P1:LELB', 'P1:RELB', 'P1:LWRA', 'P1:RWRA', 'P1:CLAV', 'P1:STRN', 'P1:LFHD', 'P1:RFHD']

# TODO: adjust for RGB data

projected_points = RGB_helpers.fix_delay(
    marker_names, c3d_data, points_3d, marker_t, T_syst_to_camera_opt, Ts_world_to_system, K, cam_res, delay, e_ts, e_us, e_vs, period, visualize=True, D=D
)

### Label with click-click method

In [8]:
import importlib
import os
import cv2
import numpy as np

importlib.reload(RGB_helpers)
from RGB_helpers import RGBLabeler

# --- Paths ---
labels_path = os.path.join(os.path.dirname(vicon_c3d_file), output_label_yml_file)

# Initialize labeler for RGB video
labeler = RGBLabeler(video_path=RGB_folder, subject="camera")

marker_names = [
 'monitor:Origin_mon_top_right',
 'monitor:mon_bottom_right',
 'monitor:mon_bottom_left',
 'monitor:mon_top_left',
 'monitor:base_origin_1',
 'monitor:base_2',
 'monitor:base_3',
 'monitor:base_4',
 'chair:origin_right_top',
 'chair:right_mid',
 'chair:right_bottom',
 'chair:left_top',
 'chair:left_bottom',
 'box2:top_right_Origin',
 'box2:bottom_right',
 'box2:bottom_left',
 'box2:top_left',
 'box1:top_1_origin',
 'box1:top_2',
 'box1:top_3',
 'box1:top_4',
 'box1:bottom_1',
 'box1:bottom_2',
 'box1:bottom_3',
 'box1:bottom_4']

# --- Correction workflow (uses projections + interactive fixing) ---
corrected_dict = labeler.correct_data_rgb(
    video_path=RGB_folder,
    period=period,
    marker_names=marker_names,
    c3d_data=c3d_data,
    points_3d=points_3d,
    marker_t=marker_t,
    T_system_to_camera=T_syst_to_camera_opt,
    T_world_to_system=Ts_world_to_system,
    K=K,
    cam_res=cam_res,
    current_delay=delay,
    D=D,
)

# Save corrected labels
labeler.save_labeled_points(labels_path)

print("Saved corrected points at:", labels_path)

cv2.destroyAllWindows()


[Frame 0] RGB time=-0.073000s, Vicon time=0.000000s
Selected position: (440, 387). Now click on the projected marker to assign.
Assigned marker 'box1:top_2' to position (440, 387)
Selected position: (442, 605). Now click on the projected marker to assign.
Assigned marker 'box1:bottom_2' to position (442, 605)
Selected position: (767, 619). Now click on the projected marker to assign.
Assigned marker 'box1:bottom_1' to position (767, 619)
Selected position: (1014, 292). Now click on the projected marker to assign.
Assigned marker 'box2:top_left' to position (1014, 292)
Selected position: (1016, 402). Now click on the projected marker to assign.
Assigned marker 'box2:bottom_left' to position (1016, 402)
Selected position: (1196, 285). Now click on the projected marker to assign.
Assigned marker 'box2:top_right_Origin' to position (1196, 285)
[Frame 1] RGB time=-0.039667s, Vicon time=0.000000s
[Frame 2] RGB time=-0.006333s, Vicon time=0.000000s
[Frame 3] RGB time=0.027000s, Vicon time=0.0

In [48]:
importlib.reload(RGB_helpers)
from helpers import ViconHelper

# Define vicon helper
vicon_helper = ViconHelper(marker_t, points_3d, delay, c3d_data.frame_count, c3d_data.point_rate, c3d_data.point_labels, True, True)

Ts_world_to_system = vicon_helper.compute_camera_marker_transforms()

# Ts_world_to_system

# Save all transformation matrices in readable 4x4 block format
output_matrices_readable = os.path.join(os.path.dirname(vicon_c3d_file), "transformation_matrices_readable.txt")

def format_matrix_block(matrix, indent=""):
    """Format a 4x4 matrix as a readable block"""
    lines = []
    for i, row in enumerate(matrix):
        if i == 0:
            row_str = "[" + " ".join([f"{val:12.8e}" for val in row])
        elif i == 3:
            row_str = " " + " ".join([f"{val:12.8e}" for val in row]) + "]"
        else:
            row_str = " " + " ".join([f"{val:12.8e}" for val in row])
        lines.append(f"{indent}{row_str}")
    return "\n".join(lines)

with open(output_matrices_readable, 'w') as f:
    f.write("# Transformation matrices from world to system coordinates\n")
    f.write("# Format: timestamp: [4x4 transformation matrix]\n\n")
    
    for i, (timestamp, transform_matrix) in enumerate(zip(marker_t, Ts_world_to_system)):
        f.write(f"{timestamp:.6f}: ")
        matrix_str = format_matrix_block(transform_matrix)
        f.write(f"{matrix_str}\n\n")

print(f"Saved readable transformation matrices to: {output_matrices_readable}")

Ts_world_to_system

out {'points': [{'stereoatis:cam_right': array([-250.65451,  590.3289 ,  881.17285], dtype=float32), 'stereoatis:cam_back': array([-329.4092,  562.3338,  927.2134], dtype=float32), 'stereoatis:cam_left': array([-283.07135,  556.2298 ,  861.2922 ], dtype=float32)}, {'stereoatis:cam_right': array([-250.68164,  590.3161 ,  881.11536], dtype=float32), 'stereoatis:cam_back': array([-329.4319 ,  562.33264,  927.15344], dtype=float32), 'stereoatis:cam_left': array([-283.11084,  556.2149 ,  861.2563 ], dtype=float32)}, {'stereoatis:cam_right': array([-250.70612,  590.31995,  881.12445], dtype=float32), 'stereoatis:cam_back': array([-329.46365,  562.3203 ,  927.12854], dtype=float32), 'stereoatis:cam_left': array([-283.13913,  556.1837 ,  861.17975], dtype=float32)}, {'stereoatis:cam_right': array([-250.7612,  590.2785,  881.1114], dtype=float32), 'stereoatis:cam_back': array([-329.48795,  562.29315,  927.0754 ], dtype=float32), 'stereoatis:cam_left': array([-283.12878,  556.2005 ,  861.19226],

[array([[ 6.34923100e-01,  6.67150259e-01,  3.89593571e-01,
         -5.26865234e+02],
        [-5.75835824e-01,  7.24679902e-02,  8.14347267e-01,
         -9.04689819e+02],
        [ 5.15058935e-01, -7.41389871e-01,  4.30180669e-01,
          1.87706726e+02],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          1.00000000e+00]]),
 array([[ 6.34890676e-01,  6.67375684e-01,  3.89260083e-01,
         -5.26706970e+02],
        [-5.75675249e-01,  7.26108700e-02,  8.14448059e-01,
         -9.04814087e+02],
        [ 5.15278280e-01, -7.41172910e-01,  4.30291623e-01,
          1.87541382e+02],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          1.00000000e+00]]),
 array([[ 6.34842575e-01,  6.67631865e-01,  3.88899267e-01,
         -5.26550049e+02],
        [-5.75523436e-01,  7.27838129e-02,  8.14539909e-01,
         -9.04950439e+02],
        [ 5.15507221e-01, -7.40925252e-01,  4.30444032e-01,
          1.87323578e+02],
        [ 0.00000000e+00,  0.00000000e+

### Project points in dynamic scene

In [50]:
importlib.reload(RGB_helpers)

# marker_names = [f"{name}" for name in c3d_data.point_labels]
# marker_names = [name.strip() for name in marker_names]

marker_names = [
 'monitor:Origin_mon_top_right',
 'monitor:mon_bottom_right',
 'monitor:mon_bottom_left',
 'monitor:mon_top_left',
 'monitor:base_origin_1',
 'monitor:base_2',
 'monitor:base_3',
 'monitor:base_4',
 'chair:origin_right_top',
 'chair:right_mid',
 'chair:right_bottom',
 'chair:left_top',
 'chair:left_bottom',
 'box2:top_right_Origin',
 'box2:bottom_right',
 'box2:bottom_left',
 'box2:top_left',
 'box1:top_1_origin',
 'box1:top_2',
 'box1:top_3',
 'box1:top_4',
 'box1:bottom_1',
 'box1:bottom_2',
 'box1:bottom_3',
 'box1:bottom_4']

delay = -0.091

projected_points = RGB_helpers.project_vicon_to_rgb_plane_dynamic(
    marker_names,
    c3d_data,
    points_3d,
    marker_t,
    T_syst_to_camera_opt,             # System → Camera transform
    Ts_world_to_system,    # World → System transforms (per frame)
    K,                     # Camera intrinsic matrix
    video_path=RGB_folder, # Path to your RGB video
    delay=delay,           # Delay loaded from init file
    visualize=False,
    video_record=True,
    D=D                    # Distortion coefficients (if any)
)
# Save projected points to text file
output_projected_points = "/home/cappe/hpe/hpe-core/datasets/vicon_processing/v2/projected_points_RGB.txt"

with open(output_projected_points, 'w') as f:
    f.write("# Format: marker_timestamp: x, y # marker_name\n")
    
    if projected_points is not None and isinstance(projected_points, dict):
        points_written = 0
        
        # Get all marker names
        all_markers = list(projected_points.keys())
        
        # Get the number of frames (assuming all markers have same length)
        if all_markers:
            first_marker_data = projected_points[all_markers[0]]
            if isinstance(first_marker_data, np.ndarray):
                num_frames = len(first_marker_data)
            else:
                num_frames = len(marker_t)
        else:
            num_frames = len(marker_t)
        
        # Iterate through each frame/timestamp
        for frame_idx in range(min(num_frames, len(marker_t))):
            marker_timestamp = marker_t[frame_idx]
            
            # For each frame, write all markers
            for marker_name in all_markers:
                marker_data = projected_points[marker_name]
                
                if isinstance(marker_data, np.ndarray):
                    if frame_idx < len(marker_data):
                        coords = marker_data[frame_idx]
                        # Check if coordinates are valid (not NaN or inf)
                        if len(coords) >= 2 and np.isfinite(coords[0]) and np.isfinite(coords[1]):
                            f.write(f"{marker_timestamp:.6f}: {coords[0]:.2f}, {coords[1]:.2f} # {marker_name}\n")
                            points_written += 1
                
                elif isinstance(marker_data, list):
                    if frame_idx < len(marker_data):
                        coords = marker_data[frame_idx]
                        if isinstance(coords, (list, tuple)) and len(coords) >= 2:
                            f.write(f"{marker_timestamp:.6f}: {coords[0]:.2f}, {coords[1]:.2f} # {marker_name}\n")
                            points_written += 1
        
        print(f"Total points written: {points_written}")
        print(f"Processed {num_frames} frames with {len(all_markers)} markers each")
    
    else:
        print("projected_points is None or not a dictionary - no data to write")

print(f"Saved projected points to: {output_projected_points}")

[Frame 0] RGB time=-0.091000s, Vicon time=0.000000s
[Frame 1] RGB time=-0.057667s, Vicon time=0.000000s
[Frame 2] RGB time=-0.024333s, Vicon time=0.000000s
[Frame 3] RGB time=0.009000s, Vicon time=0.010000s
[Frame 4] RGB time=0.042333s, Vicon time=0.040000s
[Frame 5] RGB time=0.075667s, Vicon time=0.080000s
[Frame 6] RGB time=0.109000s, Vicon time=0.110000s
[Frame 7] RGB time=0.142333s, Vicon time=0.140000s
[Frame 8] RGB time=0.175667s, Vicon time=0.180000s
[Frame 9] RGB time=0.209000s, Vicon time=0.210000s
[Frame 10] RGB time=0.242333s, Vicon time=0.240000s
[Frame 11] RGB time=0.275667s, Vicon time=0.280000s
[Frame 12] RGB time=0.309000s, Vicon time=0.310000s
[Frame 13] RGB time=0.342333s, Vicon time=0.340000s
[Frame 14] RGB time=0.375667s, Vicon time=0.380000s
[Frame 15] RGB time=0.409000s, Vicon time=0.410000s
[Frame 16] RGB time=0.442333s, Vicon time=0.440000s
[Frame 17] RGB time=0.475667s, Vicon time=0.480000s
[Frame 18] RGB time=0.509000s, Vicon time=0.510000s
[Frame 19] RGB time

### Adjust labels with on-screen projection of the points

In [ ]:
importlib.reload(RGB_helpers)
from RGB_helpers import DvsLabeler


# Define output path for corrections
corrections_path = os.path.join(os.path.dirname(vicon_c3d_file), 'corrections_labels.yml')

# Create corrector instance
corrector = DvsLabeler(img_shape=(720, 1280, 3))

# Batch correction across multiple frames
time_tags, event_indices = RGB_helpers.calc_indices(e_ts, period)

# Define marker names for correction
marker_names = ['P1:LANK', 'P1:RANK', 'P1:LWRA', 'P1:RWRA', 'P1:CLAV', 'P1:STRN', 'P1:LFHD', 'P1:RFHD', 'P1:RASI', 'P1:LASI', 'P1:LELB', 'P1:RELB', 'P1:LKNE', 'P1:RKNE', 'P1:RSHO', 'P1:LSHO']

# TODO: adjust for RGB data

corrector.correct_data(
    e_ts, e_us, e_vs, event_indices, time_tags, period, 
    marker_names, c3d_data, points_3d, marker_t, T_syst_to_camera_opt, Ts_world_to_system, 
    K, cam_res, delay, D
)

# Save corrected results automatically (using existing save_labeled_points method)
corrector.save_labeled_points(corrections_path)

print("Saved corrected points at:", corrections_path)

cv2.destroyAllWindows()

space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, skipping
space pressed, s